services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 256M  # Limita el uso de memoria
          cpus: "0.25"  # Limita el uso de CPU
    restart: always

  redis:
    image: redis:latest
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.25"
    restart: always

  airflow-webserver:
    image: apache/airflow:2.9.0
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: my-secret-key
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./scripts:/opt/airflow/scripts
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
    command: webserver
    restart: always

  airflow-scheduler:
    image: apache/airflow:2.9.0
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    depends_on:
      - postgres
      - redis
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./scripts:/opt/airflow/scripts
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.25"
    command: scheduler
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_JVMFLAGS: "-Xmx128M -Xms128M"  # Reduce uso de memoria
    ports:
      - "2181:2181"
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.25"
    restart: always

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"  # Reduce uso de memoria
    ports:
      - "9092:9092"
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
    restart: always

volumes:
  postgres_data:
  airflow_logs:
  airflow_plugins:

networks:
  airflow_network:
    driver: bridge
